version: "2"
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      - JMXDISABLE=true
  kafka:
    image: neowu/kafka:1.0.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_ARGS=--override listeners=PLAINTEXT://:9092 --override advertised.listeners=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
